export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  PASSKEY_NOT_FOUND = 'PASSKEY_NOT_FOUND',
  PASSKEY_ALREADY_EXISTS = 'PASSKEY_ALREADY_EXISTS',
  PASSKEY_VERIFICATION_FAILED = 'PASSKEY_VERIFICATION_FAILED',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  INVALID_INPUT = 'INVALID_INPUT',
  BAD_REQUEST = 'BAD_REQUEST',

  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND',

  WS_NOT_CONNECTED = 'WS_NOT_CONNECTED',

  SERVER_ERROR = 'SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_MISSING = 'TOKEN_MISSING',

  NOT_FOUND = 'NOT_FOUND',
}

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.USER_ALREADY_EXISTS]: 409,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.EMAIL_ALREADY_EXISTS]: 409,
  [ErrorCode.PHONE_ALREADY_EXISTS]: 409,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,

  [ErrorCode.PASSKEY_NOT_FOUND]: 404,
  [ErrorCode.PASSKEY_ALREADY_EXISTS]: 409,
  [ErrorCode.PASSKEY_VERIFICATION_FAILED]: 400,

  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.MISSING_REQUIRED_FIELDS]: 400,
  [ErrorCode.INVALID_INPUT]: 400,
  [ErrorCode.BAD_REQUEST]: 400,

  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.RESOURCE_ALREADY_EXISTS]: 409,
  [ErrorCode.CONNECTION_NOT_FOUND]: 404,

  [ErrorCode.WS_NOT_CONNECTED]: 400,

  [ErrorCode.SERVER_ERROR]: 500,
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,

  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.TOKEN_MISSING]: 401,

  [ErrorCode.NOT_FOUND]: 404,
};

export class AppError extends Error {
  code: ErrorCode;
  status: number;
  constructor(message: string, code: ErrorCode) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.status = ErrorHttpStatus[code];
  }
}
